#! /bin/bash
#
# usage: build xenopsd ...
# 
# This downloads and builds yum packages. 
#

set -e 

# this must match the %_topdir RPM macro
topdir=${TOPDIR:-/mnt/rpmbuild}

build()
{
  package="$1"
  sudo yum-builddep -y ${package}
  if test -f /etc/profile.d/opam.sh -a -z "$OPAMROOT"
  then
    . /etc/profile.d/opam.sh
  fi
  yumdownloader --source ${package}
  rpm -i ${package}*
  rpmbuild -ba ${topdir}/SPECS/${package}.spec
}

for p in $@; do
  build "$p"
done
