#! /bin/bash
#
# citrix [branch]
#
# Set up yum repos for Citrix-internal branch.
#

XS_BRANCH=${1:-trunk-ring3}

REPO="
[citrix]
name=XenServer 6.6 updates
baseurl=http://coltrane.uk.xensource.com/usr/groups/build/${XS_BRANCH}/latest/binary-packages/RPMS/domain0/RPMS/
gpgcheck=0
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-Citrix-6.6
enabled=1
exclude=kernel-headers

[citrix-source]
name=XenServer 6.6 updates
baseurl=http://coltrane.uk.xensource.com/usr/groups/build/${XS_BRANCH}/latest/binary-packages/RPMS/domain0/SRPMS/
gpgcheck=0
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-Citrix-6.6
enabled=1
exclude=kernel-headers
"

sudo mv /etc/yum.conf /etc/yum.conf.backup
sudo mv /etc/yum.conf.xs /etc/yum.conf
sudo echo "$REPO" > /etc/yum.repos.d.xs/Citrix.repo
