#! /bin/bash
#
# yum-setup [branch]
#
# Set up yum repos. This overwrites /etc/yum.conf with a new
# configuration.
#

set -e

BRANCH="${BRANCH:-ring3}"


if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root" 1>&2
   exit 1
fi

KEY="aHR0cDovL3hzLXl1bS1yZXBvcy5zMy13ZWJzaXRlLXVzLWVhc3QtMS5hbWF6b25hd3MuY29tLzEzMzdhYjZjLTc3YWItOWM4Yy1hOTFmLTM4ZmJhOGJlZThkZC9kb21haW4w"
while [[ $# -ge 1 ]]; do
  case "$1" in
    ely-bugfix)
      KEY="aHR0cDovL3hzLXl1bS1yZXBvcy5zMy13ZWJzaXRlLXVzLWVhc3QtMS5hbWF6b25hd3MuY29tLzQ0OWU1MmE0LTI3MWEtNDgzYS1iYWE3LTI0YmYzNjI4NjZmNy9kb21haW4w"
      BRANCH="$1"
      shift
      ;;

    dundee-bugfix)
      KEY="aHR0cDovL3hhcGktcmVwb3MuczMtd2Vic2l0ZS11cy1lYXN0LTEuYW1hem9uYXdzLmNvbS9kOGJjOGVkZi1lOGMyLTRiNmQtYjgyZi0yNGQ2NzQyZWE4YmMvZG9tYWluMA=="
      BRANCH="$1"
      shift
      ;;

    *)
      BRANCH="$1"
      shift
      ;;
  esac
done
echo "BRANCH=$BRANCH"
YUM="$(echo $KEY | base64 --decode)"

YUM_CONF_PUBLIC='
[main]
cachedir=/var/cache/yum/$basearch/$releasever
keepcache=0
debuglevel=2
logfile=/var/log/yum.log
exactarch=1
obsoletes=1
gpgcheck=1
plugins=1
installonly_limit=5
bugtracker_url=http://bugs.centos.org/set_project.php?project_id=23&ref=http://bugs.centos.org/bug_report_page.php?category=yum
distroverpkg=centos-release
override_install_langs=en_US.UTF-8
tsflags=nodocs
'

XS_REPO_PUBLIC="
[xs]
name=XenServer
baseurl=$YUM
enabled=1
gpgcheck=0
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-Citrix-6.6
exclude=xenserver-release
"

# write configuration files

B=${B:-}
mkdir -p                  $B/etc/yum.repos.d
echo "$YUM_CONF_PUBLIC" > $B/etc/yum.conf
echo "$XS_REPO_PUBLIC"  > $B/etc/yum.repos.d/xs.repo

