#! /bin/bash
#
# yum-setup [branch]
#
# Set up yum repos. This overwrites /etc/yum.conf with a new
# configuration.
#

set -e

if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root" 1>&2
   exit 1
fi

case "$1" in
  dundee-bugfix)
    KEY=aHR0cDovL3hhcGktcmVwb3MuczMtd2Vic2l0ZS11cy1lYXN0LTEuYW1hem9uYXdzLmNvbS9kOGJjOGVkZi1lOGMyLTRiNmQtYjgyZi0yNGQ2NzQyZWE4YmMvZG9tYWluMA==
    ;;
  ely-bugfix)
    KEY=aHR0cDovL3hhcGktcmVwb3MuczMtd2Vic2l0ZS11cy1lYXN0LTEuYW1hem9uYXdzLmNvbS80NDllNTJhNC0yNzFhLTQ4M2EtYmFhNy0yNGJmMzYyODY2ZjcvZG9tYWluMA==
    ;;
  falcon)
    KEY=aHR0cDovL3hhcGktcmVwb3MuczMtd2Vic2l0ZS11cy1lYXN0LTEuYW1hem9uYXdzLmNvbS9mYTdjMGVhOS05ZDMxLTUwYmItYThkNi04YWUzNjdlZjJmMTQvZG9tYWluMA==
    ;;
  feature-CBT)
    KEY=aHR0cDovL3hhcGktcmVwb3MuczMtd2Vic2l0ZS11cy1lYXN0LTEuYW1hem9uYXdzLmNvbS9mZWE3NjJlNy1jYjcwLTRiZTktZWY4Ni00M2FlODlmOTFjZDIvZG9tYWluMA==
    ;;
  qemu-upstream)
    KEY=aHR0cDovL3hhcGktcmVwb3MuczMtd2Vic2l0ZS11cy1lYXN0LTEuYW1hem9uYXdzLmNvbS83ZWEzNzIxMi05MDc5LWUzMjEtNTdhYi0xZTQ5ZWFmYzBkY2YvZG9tYWluMA==
    ;;
  vgpu-migration)
    KEY=aHR0cDovL3hhcGktcmVwb3MuczMtd2Vic2l0ZS11cy1lYXN0LTEuYW1hem9uYXdzLmNvbS9hNjIxMTk2MS04ZGFkLTQzYjctOGFlMy1iOTQ0YzIxNzkxNGEvZG9tYWluMA==
    ;;
  usb-passthrough)
    KEY=aHR0cDovL3hhcGktcmVwb3MuczMtd2Vic2l0ZS11cy1lYXN0LTEuYW1hem9uYXdzLmNvbS8wMDViYmE1Mi03ZmIzLTlhMmMtZDY5MS1hOGI1Yjg5N2NmZjMvZG9tYWluMA==
    ;;
  *)
    KEY=aHR0cDovL3hhcGktcmVwb3MuczMtd2Vic2l0ZS11cy1lYXN0LTEuYW1hem9uYXdzLmNvbS8xMzM3YWI2Yy03N2FiLTljOGMtYTkxZi0zOGZiYThiZWU4ZGQvZG9tYWluMA==
  ;;
esac

YUM="$(echo $KEY | base64 --decode)"
echo "$YUM"

YUM_CONF_PUBLIC='
[main]
cachedir=/var/cache/yum/$basearch/$releasever
keepcache=0
debuglevel=2
logfile=/var/log/yum.log
exactarch=1
obsoletes=1
gpgcheck=1
plugins=1
installonly_limit=5
bugtracker_url=http://bugs.centos.org/set_project.php?project_id=23&ref=http://bugs.centos.org/bug_report_page.php?category=yum
distroverpkg=centos-release
override_install_langs=en_US.UTF-8
tsflags=nodocs
'

XS_REPO_PUBLIC="
[xs]
name=XenServer
baseurl=$YUM
enabled=1
gpgcheck=0
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-Citrix-6.6
exclude=xenserver-release
"

# write configuration files

B=${B:-}
mkdir -p                  $B/etc/yum.repos.d
echo "$YUM_CONF_PUBLIC" > $B/etc/yum.conf
echo "$XS_REPO_PUBLIC"  > $B/etc/yum.repos.d/xs.repo

